### ISSUE TITLE
Update Register field verification

### ISSUE THREAD

**Issue by TylerMathis** [ucf-tower-app/mobile#87]
When creating a new account, we are now limiting the registration fields to the following restrictions.

```yaml
email: valid email format
username: 5 <= len <= 15, lowercase a-z
displayName: 5 <= len <= 30, lower/uppercase and spaces
password: len >= 8
```
